# ==============================
# Application
# ==============================
spring.application.name=urlshortener
server.port=8080

# ==============================
# MySQL Configuration
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# Redis Configuration (Railway Production)
# ==============================
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.username=${REDISUSER:default}   # default if Railway username not set
spring.data.redis.password=${REDISPASSWORD}       # must match Railway Redis password
spring.data.redis.ssl.enabled=false

## Optional: Cache settings
#spring.cache.type=redis
#spring.cache.redis.time-to-live=600000   # 10 minutes